version: '3.8'

services:
  web:
    build: .
    container_name: faq_project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: faqdb
      POSTGRES_USER: faquser
      POSTGRES_PASSWORD: faqpassword
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
